services:
  flask_app:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11400:11400"
    volumes:
      - ollama_models:/root/.ollama/models
    command: ["ollama", "serve"]

volumes:
  ollama_models:
